set(_CATKIN_CURRENT_PACKAGE "cv_bridge")
set(cv_bridge_VERSION "1.12.0")
set(cv_bridge_MAINTAINER "Vincent Rabaud <vincent.rabaud@gmail.com>")
set(cv_bridge_BUILD_DEPENDS "boost" "opencv3" "python" "rosconsole" "sensor_msgs")
set(cv_bridge_RUN_DEPENDS "boost" "opencv3" "python" "rosconsole" "sensor_msgs")
set(cv_bridge_DEPRECATED "")
set(cv_bridge_BUILDTOOL_DEPENDS "catkin")
set(cv_bridge_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.68")