set(_CATKIN_CURRENT_PACKAGE "manual_control")
set(manual_control_VERSION "0.0.0")
set(manual_control_MAINTAINER "zargol <zahra.boroujeni@gmail.com>")
set(manual_control_PACKAGE_FORMAT "1")
set(manual_control_BUILD_DEPENDS "roscpp" "sensor_msgs" "motor_communication" "send_steering")
set(manual_control_BUILD_EXPORT_DEPENDS "motor_communication" "send_steering")
set(manual_control_BUILDTOOL_DEPENDS "catkin")
set(manual_control_BUILDTOOL_EXPORT_DEPENDS )
set(manual_control_EXEC_DEPENDS "motor_communication" "send_steering")
set(manual_control_RUN_DEPENDS "motor_communication" "send_steering")
set(manual_control_TEST_DEPENDS )
set(manual_control_DOC_DEPENDS )
set(manual_control_DEPRECATED "")