set(_CATKIN_CURRENT_PACKAGE "heading")
set(heading_MAINTAINER "zargol <zahra.boroujeni@gmail.com>")
set(heading_DEPRECATED "")
set(heading_VERSION "0.0.0")
set(heading_BUILD_DEPENDS "roscpp" "serial" "std_msgs")
set(heading_RUN_DEPENDS "roscpp" "serial" "std_msgs")
set(heading_BUILDTOOL_DEPENDS "catkin")