(cl:defpackage realsense_camera-srv
  (:use )
  (:export
   "CAMERACONFIGURATION"
   "<CAMERACONFIGURATION-REQUEST>"
   "CAMERACONFIGURATION-REQUEST"
   "<CAMERACONFIGURATION-RESPONSE>"
   "CAMERACONFIGURATION-RESPONSE"
  ))

