set(_CATKIN_CURRENT_PACKAGE "rplidar_ros")
set(rplidar_ros_MAINTAINER "Ling <mickey.leen@gmail.com>")
set(rplidar_ros_DEPRECATED "")
set(rplidar_ros_VERSION "1.0.1")
set(rplidar_ros_BUILD_DEPENDS "roscpp" "rosconsole" "sensor_msgs" "std_srvs")
set(rplidar_ros_RUN_DEPENDS "roscpp" "rosconsole" "sensor_msgs" "std_srvs")
set(rplidar_ros_BUILDTOOL_DEPENDS "catkin")