set(_CATKIN_CURRENT_PACKAGE "ip_mapping")
set(ip_mapping_VERSION "0.0.0")
set(ip_mapping_MAINTAINER "zargol <zahra.boroujeni@gmail.com>")
set(ip_mapping_PACKAGE_FORMAT "1")
set(ip_mapping_BUILD_DEPENDS "roscpp" "sensor_msgs" "cv_bridge" "pcl_ros" "std_msgs")
set(ip_mapping_BUILD_EXPORT_DEPENDS "roscpp" "sensor_msgs" "cv_bridge" "pcl_ros" "std_msgs")
set(ip_mapping_BUILDTOOL_DEPENDS "catkin")
set(ip_mapping_BUILDTOOL_EXPORT_DEPENDS )
set(ip_mapping_EXEC_DEPENDS "roscpp" "sensor_msgs" "cv_bridge" "pcl_ros" "std_msgs")
set(ip_mapping_RUN_DEPENDS "roscpp" "sensor_msgs" "cv_bridge" "pcl_ros" "std_msgs")
set(ip_mapping_TEST_DEPENDS )
set(ip_mapping_DOC_DEPENDS )
set(ip_mapping_DEPRECATED "")