set(_CATKIN_CURRENT_PACKAGE "send_steering")
set(send_steering_VERSION "0.0.0")
set(send_steering_MAINTAINER "zargol <zahra.boroujeni@gmail.com>")
set(send_steering_PACKAGE_FORMAT "1")
set(send_steering_BUILD_DEPENDS "serial" "roscpp" "sensor_msgs" "std_msgs")
set(send_steering_BUILD_EXPORT_DEPENDS "serial" "roscpp" "sensor_msgs" "std_msgs")
set(send_steering_BUILDTOOL_DEPENDS "catkin" "catkin")
set(send_steering_BUILDTOOL_EXPORT_DEPENDS )
set(send_steering_EXEC_DEPENDS "serial" "roscpp" "sensor_msgs" "std_msgs")
set(send_steering_RUN_DEPENDS "serial" "roscpp" "sensor_msgs" "std_msgs")
set(send_steering_TEST_DEPENDS )
set(send_steering_DOC_DEPENDS )
set(send_steering_DEPRECATED "")