#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export LD_LIBRARY_PATH="/root/catkin_ws/odroid-devel/lib/x86_64-linux-gnu:/opt/odroid-x2/sdk/opt/ros/indigo/lib/x86_64-linux-gnu:/opt/odroid-x2/sdk//opt/ros/indigo/lib/x86_64-linux-gnu:/root/catkin_ws/odroid-devel/lib:/opt/odroid-x2/sdk/opt/ros/indigo/lib:/opt/odroid-x2/sdk/opt/ros/indigo/lib/arm-linux-gnueabihf:/opt/odroid-x2/sdk//opt/ros/indigo/lib:/opt/odroid-x2/sdk//opt/ros/indigo/lib/arm-linux-gnueabihf:/home/zargol/catkin_work_space/devel/lib/x86_64-linux-gnu:/opt/ros/indigo/lib/x86_64-linux-gnu:/home/zargol/catkin_ws/devel/lib:/home/zargol/catkin_ws/install/lib:/opt/ros/indigo/lib/python2.7/dist-packages:/opt/ros/indigo/lib/python2.7/dist-packages:/opt/ros/indigo/lib/python2.7/dist-packages"
export PKG_CONFIG_PATH="/root/catkin_ws/odroid-devel/lib/x86_64-linux-gnu/pkgconfig:/opt/odroid-x2/sdk/opt/ros/indigo/lib/x86_64-linux-gnu/pkgconfig:/opt/odroid-x2/sdk//opt/ros/indigo/lib/x86_64-linux-gnu/pkgconfig:/root/catkin_ws/odroid-devel/lib/pkgconfig:/opt/odroid-x2/sdk/opt/ros/indigo/lib/pkgconfig:/opt/odroid-x2/sdk/opt/ros/indigo/lib/arm-linux-gnueabihf/pkgconfig:/opt/odroid-x2/sdk//opt/ros/indigo/lib/pkgconfig:/opt/odroid-x2/sdk//opt/ros/indigo/lib/arm-linux-gnueabihf/pkgconfig:/home/zargol/catkin_work_space/devel/lib/x86_64-linux-gnu/pkgconfig:/opt/ros/indigo/lib/x86_64-linux-gnu/pkgconfig:/home/zargol/catkin_ws/devel/lib/pkgconfig:/home/zargol/catkin_ws/install/lib/pkgconfig"
export ROS_PACKAGE_PATH="/root/catkin_ws/src/odometry:/root/catkin_ws/src/control:/root/catkin_ws/src/auto_stop:/root/catkin_ws/src/cv_bridge:/root/catkin_ws/src/random_movement:/root/catkin_ws/src/rplidar_ros:/root/catkin_ws/src/usb_cam:/root/catkin_ws/src/serial:/root/catkin_ws/src/cmvision:/root/catkin_ws/src/ip_mapping:/root/catkin_ws/src/line_detection:/root/catkin_ws/src/realsense_camera:/root/catkin_ws/src/heading:/root/catkin_ws/src/line_detection:/root/catkin_ws/src/light:/root/catkin_ws/src/motor_communication:/root/catkin_ws/src/send_steering:/root/catkin_ws/src/detect_roof_rectangles
:/root/catkin_ws/src/detect_roof_rectangles:/opt/odroid-x2/sdk/opt/ros/indigo/share:/opt/odroid-x2/sdk/opt/ros/indigo/stacks:/opt/odroid-x2/sdk//opt/ros/indigo/share:/opt/odroid-x2/sdk//opt/ros/indigo/stacks"