# CMake generated Testfile for 
# Source directory: /home/ros/model_car/catkin_ws/src/cv_bridge/test
# Build directory: /home/ros/model_car/catkin_ws/odroid-build/cv_bridge/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(_ctest_cv_bridge_gtest_cv_bridge-utest "/home/ros/model_car/catkin_ws/odroid-build/cv_bridge/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/odroid-x2/sdk/opt/ros/indigo/share/catkin/cmake/test/run_tests.py" "/home/ros/model_car/catkin_ws/odroid-build/cv_bridge/test_results/cv_bridge/gtest-cv_bridge-utest.xml" "--return-code" "/home/ros/model_car/catkin_ws/odroid-devel/lib/cv_bridge/cv_bridge-utest --gtest_output=xml:/home/ros/model_car/catkin_ws/odroid-build/cv_bridge/test_results/cv_bridge/gtest-cv_bridge-utest.xml")
ADD_TEST(_ctest_cv_bridge_nosetests_enumerants.py "/home/ros/model_car/catkin_ws/odroid-build/cv_bridge/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/odroid-x2/sdk/opt/ros/indigo/share/catkin/cmake/test/run_tests.py" "/home/ros/model_car/catkin_ws/odroid-build/cv_bridge/test_results/cv_bridge/nosetests-enumerants.py.xml" "--return-code" "/usr/bin/cmake -E make_directory /home/ros/model_car/catkin_ws/odroid-build/cv_bridge/test_results/cv_bridge" "/usr/bin/nosetests-2.7 -P --process-timeout=60 /home/ros/model_car/catkin_ws/src/cv_bridge/test/enumerants.py --with-xunit --xunit-file=/home/ros/model_car/catkin_ws/odroid-build/cv_bridge/test_results/cv_bridge/nosetests-enumerants.py.xml")
ADD_TEST(_ctest_cv_bridge_nosetests_python_bindings.py "/home/ros/model_car/catkin_ws/odroid-build/cv_bridge/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/odroid-x2/sdk/opt/ros/indigo/share/catkin/cmake/test/run_tests.py" "/home/ros/model_car/catkin_ws/odroid-build/cv_bridge/test_results/cv_bridge/nosetests-python_bindings.py.xml" "--return-code" "/usr/bin/cmake -E make_directory /home/ros/model_car/catkin_ws/odroid-build/cv_bridge/test_results/cv_bridge" "/usr/bin/nosetests-2.7 -P --process-timeout=60 /home/ros/model_car/catkin_ws/src/cv_bridge/test/python_bindings.py --with-xunit --xunit-file=/home/ros/model_car/catkin_ws/odroid-build/cv_bridge/test_results/cv_bridge/nosetests-python_bindings.py.xml")
