// Generated by gencpp from file realsense_camera/cameraConfiguration.msg
// DO NOT EDIT!


#ifndef REALSENSE_CAMERA_MESSAGE_CAMERACONFIGURATION_H
#define REALSENSE_CAMERA_MESSAGE_CAMERACONFIGURATION_H

#include <ros/service_traits.h>


#include <realsense_camera/cameraConfigurationRequest.h>
#include <realsense_camera/cameraConfigurationResponse.h>


namespace realsense_camera
{

struct cameraConfiguration
{

typedef cameraConfigurationRequest Request;
typedef cameraConfigurationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct cameraConfiguration
} // namespace realsense_camera


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::realsense_camera::cameraConfiguration > {
  static const char* value()
  {
    return "2c284890309b239ca006a289ca29b4d1";
  }

  static const char* value(const ::realsense_camera::cameraConfiguration&) { return value(); }
};

template<>
struct DataType< ::realsense_camera::cameraConfiguration > {
  static const char* value()
  {
    return "realsense_camera/cameraConfiguration";
  }

  static const char* value(const ::realsense_camera::cameraConfiguration&) { return value(); }
};


// service_traits::MD5Sum< ::realsense_camera::cameraConfigurationRequest> should match 
// service_traits::MD5Sum< ::realsense_camera::cameraConfiguration > 
template<>
struct MD5Sum< ::realsense_camera::cameraConfigurationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_camera::cameraConfiguration >::value();
  }
  static const char* value(const ::realsense_camera::cameraConfigurationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_camera::cameraConfigurationRequest> should match 
// service_traits::DataType< ::realsense_camera::cameraConfiguration > 
template<>
struct DataType< ::realsense_camera::cameraConfigurationRequest>
{
  static const char* value()
  {
    return DataType< ::realsense_camera::cameraConfiguration >::value();
  }
  static const char* value(const ::realsense_camera::cameraConfigurationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::realsense_camera::cameraConfigurationResponse> should match 
// service_traits::MD5Sum< ::realsense_camera::cameraConfiguration > 
template<>
struct MD5Sum< ::realsense_camera::cameraConfigurationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_camera::cameraConfiguration >::value();
  }
  static const char* value(const ::realsense_camera::cameraConfigurationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_camera::cameraConfigurationResponse> should match 
// service_traits::DataType< ::realsense_camera::cameraConfiguration > 
template<>
struct DataType< ::realsense_camera::cameraConfigurationResponse>
{
  static const char* value()
  {
    return DataType< ::realsense_camera::cameraConfiguration >::value();
  }
  static const char* value(const ::realsense_camera::cameraConfigurationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REALSENSE_CAMERA_MESSAGE_CAMERACONFIGURATION_H
