set(_CATKIN_CURRENT_PACKAGE "usb_cam")
set(usb_cam_MAINTAINER "Russell Toris <rctoris@wpi.edu>")
set(usb_cam_DEPRECATED "")
set(usb_cam_VERSION "0.3.4")
set(usb_cam_BUILD_DEPENDS "image_transport" "roscpp" "std_msgs" "std_srvs" "sensor_msgs" "ffmpeg" "camera_info_manager")
set(usb_cam_RUN_DEPENDS "image_transport" "roscpp" "std_msgs" "std_srvs" "sensor_msgs" "ffmpeg" "camera_info_manager" "v4l-utils")
set(usb_cam_BUILDTOOL_DEPENDS "catkin")