set(_CATKIN_CURRENT_PACKAGE "motor_communication")
set(motor_communication_VERSION "0.0.0")
set(motor_communication_MAINTAINER "zargol <zahra.boroujeni@gmail.com>")
set(motor_communication_PACKAGE_FORMAT "1")
set(motor_communication_BUILD_DEPENDS "serial" "roscpp" "std_msgs" "geometry_msgs")
set(motor_communication_BUILD_EXPORT_DEPENDS "serial" "roscpp" "std_msgs" "geometry_msgs")
set(motor_communication_BUILDTOOL_DEPENDS "catkin" "catkin")
set(motor_communication_BUILDTOOL_EXPORT_DEPENDS )
set(motor_communication_EXEC_DEPENDS "serial" "roscpp" "std_msgs" "geometry_msgs")
set(motor_communication_RUN_DEPENDS "serial" "roscpp" "std_msgs" "geometry_msgs")
set(motor_communication_TEST_DEPENDS )
set(motor_communication_DOC_DEPENDS )
set(motor_communication_DEPRECATED "")