set(_CATKIN_CURRENT_PACKAGE "visual_gps")
set(visual_gps_MAINTAINER "zargol <zargol@todo.todo>")
set(visual_gps_DEPRECATED "")
set(visual_gps_VERSION "0.0.0")
set(visual_gps_BUILD_DEPENDS "rosconsole" "rostime" "roscpp_serialization" "geometry_msgs" "roscpp" "std_msgs" "tf" "message_generation" "detect_roof_rectangles")
set(visual_gps_RUN_DEPENDS "geometry_msgs" "roscpp" "std_msgs" "tf" "message_runtime" "detect_roof_rectangles")
set(visual_gps_BUILDTOOL_DEPENDS "catkin")